create table PRODUCT(
    PRODUCTNO VARCHAR2(200 BYTE),
    CATEGORYNO VARCHAR2(200 BYTE),
    SIZENO VARCHAR2(200 BYTE),
    COLORNO VARCHAR2(200 BYTE),
    PRODUCTNAME VARCHAR2(200 BYTE),
    RECEIVINGDATE DATE ,
    PRODUCTSTOCK NUMBER ,
    INQUANTITY VARCHAR2(200 BYTE),
    COST NUMBER,
    PRICE NUMBER
);

CREATE TABLE PRODUCTCATEGORY(
    CATEGORYNO VARCHAR2(200 BYTE),
    CATEGORYNAME VARCHAR2(200 BYTE)
);

CREATE TABLE PRODUCTREVIEW(
    REVIEWNO VARCHAR2(200 BYTE),
    PRODUCTNO VARCHAR2(200 BYTE),
    BUYWRITER VARCHAR2(200 BYTE),
    PRODUCTSCORE NUMBER,
    PRODUCTCONTENT VARCHAR2(200 BYTE)
);

CREATE TABLE PRODREVIEWREPLY(
    REVIEWNO VARCHAR2(200 BYTE),
    MANAGERWRITER VARCHAR2(200 BYTE),
    REVIEWREPLYCONTENT VARCHAR2(200 BYTE)
);

CREATE TABLE MEMBER(
    MEMBERID VARCHAR2(200 BYTE),
    PW VARCHAR2(200 BYTE),
    MEMBERNAME VARCHAR2(200 BYTE),
    ADDRESS VARCHAR2(200 BYTE),
    BIRTHDATE DATE,
    MEMBERTELNO VARCHAR2(200 BYTE),
    WITHDRAW VARCHAR2(200 BYTE) CONSTRAINT WITHDRAW_CHECK CHECK(WITHDRAW IN ('0', '1')),
    GENDER VARCHAR2(200 BYTE) CONSTRAINT GENDER_CHECK CHECK(GENDER IN ('M','F'))
);

CREATE TABLE GUEST(
    GUESTTELNO VARCHAR2(200 BYTE),
    GUESTPW VARCHAR2(200 BYTE)
);

CREATE TABLE CART(
    PRODUCTNO VARCHAR2(200 BYTE),
    MEMBERID VARCHAR2(200 BYTE),
    GUESTTELNO VARCHAR2(200 BYTE)
);

CREATE TABLE WISHLIST(
    PRODUCTNO VARCHAR2(200 BYTE),
    MEMBERID VARCHAR2(200 BYTE),
    GUESTTELNO VARCHAR2(200 BYTE)
);

CREATE TABLE MEMBERORDER(
    MEMBERORDERNO VARCHAR2(200 BYTE),
    PRODUCTNO VARCHAR2(200 BYTE),
    MEMBERID VARCHAR2(200 BYTE),
    ORDERQUANTITY NUMBER,
    PRICESUM NUMBER,
    POSTNO VARCHAR2(200 BYTE),
    ADDRESS VARCHAR2(200 BYTE),
    ADDRESSDETAIL VARCHAR2(200 BYTE)
);

CREATE TABLE GUESTORDER(
    GUESTORDERNO VARCHAR2(200 BYTE),
    PRODUCTNO VARCHAR2(200 BYTE),
    ORDERQUANTITY NUMBER,
    PRICESUM NUMBER,
    POSTNO VARCHAR2(200 BYTE),
    ADDRESS VARCHAR2(200 BYTE),
    ADDRESSDETAIL VARCHAR2(200 BYTE),
    GUESTTELNO VARCHAR2(200 BYTE),
    GUESTNAME VARCHAR2(200 BYTE)
);

CREATE TABLE MEMBERREFUND(
REFUNDNO VARCHAR2(200 BYTE),
MEMBERORDERNO VARCHAR2(200 BYTE),
REFUNDREASON VARCHAR2(200 BYTE),
REASONPHOTO VARCHAR2(200 BYTE),
MEMBERID VARCHAR2(200 BYTE)
);

CREATE TABLE GUESTREFUND(
    REFUNDNO VARCHAR2(200 BYTE),
    GUESTORDERNO VARCHAR2(200 BYTE),
    REFUNDREASON VARCHAR2(200 BYTE),
    REASONPHOTO VARCHAR2(200 BYTE),
    GUESTTELNO VARCHAR2(200 BYTE)
);

CREATE TABLE PRODUCTPHOTO(
PRODUCTPHOTONO VARCHAR2(200 BYTE),
PRODUCTNO VARCHAR2(200 BYTE),
PHOTOPATH VARCHAR2(200 BYTE)
);

CREATE TABLE QNA(
    QNANO VARCHAR2(200 BYTE),
    MEMBERID VARCHAR2(200 BYTE),
    QNACONTENT VARCHAR2(200 BYTE),
    QNAREPLY VARCHAR2(200 BYTE)
);

CREATE TABLE PRODUCTINQUIRY(
    PRODUCTINQNO VARCHAR2(200 BYTE),
    MEMBERID VARCHAR2(200 BYTE),
    PRODUCTINQCONT VARCHAR2(200 BYTE),
    PRODINQRE VARCHAR2(200 BYTE)
);

CREATE TABLE PRODUCTCOLOR(
COLORNO VARCHAR2(200 BYTE),
COLORNAME VARCHAR2(200 BYTE),
PRODUCTNO VARCHAR2(200 BYTE)
);

CREATE TABLE PRODUCTSIZE(
SIZENO VARCHAR2(200 BYTE),
SIZEKIND VARCHAR2(200 BYTE),
PRODUCTNO VARCHAR2(200 BYTE)
);

CREATE TABLE MANAGER(
MANAGERNO VARCHAR2(200 BYTE),
MANAGERNAME VARCHAR2(200 BYTE)
);

COMMIT;
----------------------------------------------------

ALTER TABLE PRODUCT
ADD CONSTRAINT pk_PRODUCTNO PRIMARY KEY (PRODUCTNO);


ALTER TABLE PRODUCTCATEGORY
ADD CONSTRAINT pk_CATEGORYNO PRIMARY KEY (CATEGORYNO);


ALTER TABLE PRODUCTREVIEW
ADD CONSTRAINT pk_REVIEWNO PRIMARY KEY (REVIEWNO);

ALTER TABLE PRODREVIEWREPLY
ADD REPLYNO VARCHAR2(200 BYTE); 
ALTER TABLE PRODREVIEWREPLY
ADD CONSTRAINT pk_REPLYNO PRIMARY KEY (REPLYNO);

ALTER TABLE MEMBERORDER
ADD CONSTRAINT pk_MEMBERORDERNO PRIMARY KEY (MEMBERORDERNO);

ALTER TABLE GUESTORDER
ADD CONSTRAINT pk_GUESTORDERNO PRIMARY KEY (GUESTORDERNO);

ALTER TABLE MEMBERREFUND
ADD CONSTRAINT pk_MREFUNDNO PRIMARY KEY (MREFUNDNO);

ALTER TABLE GUESTREFUND
ADD CONSTRAINT pk_GREFUNDNO PRIMARY KEY (GREFUNDNO);

ALTER TABLE PRODUCTPHOTO
ADD CONSTRAINT pk_PRODUCTPHOTONO PRIMARY KEY (PRODUCTPHOTONO);

ALTER TABLE QNA
ADD CONSTRAINT pk_QNANO PRIMARY KEY (QNANO);

ALTER TABLE PRODUCTINQUIRY
ADD CONSTRAINT pk_PRODUCTINQNO PRIMARY KEY (PRODUCTINQNO);

ALTER TABLE PRODUCTCOLOR
ADD CONSTRAINT pk_COLORNO PRIMARY KEY (COLORNO);

ALTER TABLE PRODUCTSIZE
ADD CONSTRAINT pk_SIZENO PRIMARY KEY (SIZENO);

ALTER TABLE MANAGER
ADD CONSTRAINT pk_MANAGERNO PRIMARY KEY (MANAGERNO);
